<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>gameshare-admin</AssemblyName>
    <RootNamespace>GameShare.Admin</RootNamespace>
    <SatelliteResourceLanguages>cs;en</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameShare.Protocol\GameShare.Protocol.csproj" />
    <ProjectReference Include="..\GameShare.Storage\GameShare.Storage.csproj" />
  </ItemGroup>

</Project>
